// POSTS
export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST'
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR'

// CATEGORIES
export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR'

// SUBSCRIPTION
export const SAVE_EMAIL_REQUEST = 'SAVE_EMAIL_REQUEST'
export const SAVE_EMAIL_SUCCESS = 'SAVE_EMAIL_SUCCESS'
export const SAVE_EMAIL_ERROR = 'SAVE_EMAIL_ERROR'
